### ISSUE TITLE
error in node modules

### ISSUE THREAD

**Issue by quavo19** [AbdullahAnsarii/rn-story#2]
Hello, my name is Donald, and I am currently working on the development of a social media app. I am utilizing this specific library for my project, and I have encountered a few issues that I would like you to address. Please kindly review the details below, and I would appreciate any assistance or guidance you can provide. Thank you.
![Screenshot (188)](https://github.com/AbdullahAnsarii/rn-story/assets/87555548/e613ae2d-e651-45a2-abe5-ffcd2d9fc402)
it clearly says `React does not exist` 
when i enter the folder directory in the node modules and import react, it works fine. but I don't think that solution will help me in the long run since i dont push node-modules to production. is there any other way to resolve this?

**Comment by AbdullahAnsarii** [comment]
Hi @quavo19 ,

Thank you for opening the issue and bringing my attention to this, according to this issue [check here](https://github.com/facebook/metro/issues/646) it is because of some babel configuration. The package is working fine for me and a few other people who I asked to test (which is strange). I have published the new version with the updated babel configuration please check [1.2.5 (rn-story)](https://www.npmjs.com/package/rn-story) and let me know if this resolves the issue.

**Comment by quavo19** [comment]
@AbdullahAnsarii thank you very much for the reply. and sorry fro responding late. I solved it. but now there's a feature I want to add, I want the `onAllStoriesEnd ` function to move to the next user stories. it says in the readme that I have to update the index but I don't know which index to update. and I was hoping if you could help. it would make my work easier, thank you
